### ISSUE TITLE
Xcode 9 New Build System: Info.plist is produced by multiple commands

### ISSUE THREAD

**Issue by zanomar1** [Ceskasporitelna/cs-locker-ui-sdk-ios#11]
We're trying to get Xcode 9's New Build System to work for our project and encountered a small hiccup on the way.
When running a clean build after `pod install` I'm running into a `node is produced by multiple commands` issue:

```
unable to build node: '/Users/marcel/Library/Developer/Xcode/DerivedData/George_Go-cqkuynxdluakwmbsjtbmobwcnurg/Build/Products/Debug-iphonesimulator/CSLockerUI/CSLockerUI.bundle/Info.plist'

node is produced by multiple commands; e.g.:
'ffc8d4025b171e3ebeb3063a904d251b2ca8a1499cdec391c17e49f1732fa3e2:CopyPlistFile /Users/marcel/Library/Developer/Xcode/DerivedData/George_Go-cqkuynxdluakwmbsjtbmobwcnurg/Build/Products/Debug-iphonesimulator/CSLockerUI/CSLockerUI.bundle/Info.plist /Users/marcel/beeone/george-app-ios/Pods/CSLockerUI/LockerUI/Info.plist' 

and 

'ffc8d4025b171e3ebeb3063a904d251b2ca8a1499cdec391c17e49f1732fa3e2:ProcessInfoPlistFile /Users/marcel/Library/Developer/Xcode/DerivedData/George_Go-cqkuynxdluakwmbsjtbmobwcnurg/Build/Products/Debug-iphonesimulator/CSLockerUI/CSLockerUI.bundle/Info.plist /Users/marcel/beeone/george-app-ios/Pods/Target Support Files/CSLockerUI/ResourceBundle-CSLockerUI-Info.plist'
```

It seems like the issue with the duplicate .plist entry lies in the definition of the "resource bundle" in the `CSLockerUI.podspec` file (L:39):

```
  s.resource_bundle = { 'CSLockerUI' => [
        'LockerUI/*.{xib,storyboard,strings,xcconfig,plist,modulemap}',    # is plist in this case necessary?
        'LockerUI/*.lproj'
    ] }
```

I'm not a 100% sure if the `Info.plist` is needed as part of the bundle, but removing it from the `CSLockerUI-CSLockerUI` bundle target's "Copy Bundle Resources" phase (in `Pods.xcodeproj`) resolved the issue in our case. By integrating locker-ui as a development pod and modifying the podspec I verified that removing the `plist` file ending from `s.resource_bundle` results in the desired "Copy Bundle Resources" phase (without the plist in it).

Could you give any insights in the usage of the `Info.plist` in this case or even remove it safely from your podspec?

Thanks in advance

**Comment by zanomar1** [comment]
Btw. I wanted to create a fork and a PR with the change, but it seems that I don't have the permission to do so.

**Comment by nevyhostenyv** [comment]
Hello,

 

Did you try to remove the DerivedData folder before build?

 

Regards

 

Vladimír Nevyhoštěný

**Comment by zanomar1** [comment]
Yes, I did.

**Comment by hauseja3** [comment]
@zanomar1 Thanks for your advice, we will try to safely clean up `CSLockerUI.podspec` file. 👍

**Comment by zanomar1** [comment]
hey @hauseja3, any updates that you could give us? 🙂

**Comment by hauseja3** [comment]
Hi @zanomar1, we are releasing (right now) new version of core + locker-ui sdks after swift 4 migration. After we migrated our projects, we **were not able to reproduce** your bug. I will ping you after new versions are released, so you can test it as well.

**Comment by hauseja3** [comment]
Hi @zanomar1, could you please test new versions?

`"CSCoreSDK", "~> 2.0"`
`"CSLockerUISDK", "~> 3.0"`

**Comment by zanomar1** [comment]
Ah, great! Will try it out right away, thank you!

**Comment by zanomar1** [comment]
Hey @hauseja3,
Sorry to say - but I'm running in the same issue as before when using the Xcode 9 New Build System. 😕 

In our project we're still on Swift 3.2, so to be sure I created an empty project using Swift 4 and New Build System and integrated the new SDK versions. It builds fine with Swift 4 and Standard Build System but fails with the duplicate .plist entry for New Build System.

I would be happy to share this example project with you, please just tell me where or how.

Thank you for your efforts!

**Comment by hauseja3** [comment]
Hi @zanomar1, I would appreciate it, because we cannot reproduce it. Could you please send me link to the repo or `.zip` to my email address jan.hauser@applifting.cz?

**Comment by zanomar1** [comment]
Thanks, I sent you an email.

**Comment by hauseja3** [comment]
Hi @zanomar1, unfortunately it still builds ok. My console output is in attachment, then I opened XCode workspace and it successfully built. 

<img width="499" alt="screen shot 2017-11-28 at 12 43 28" src="https://user-images.githubusercontent.com/13918426/33318165-f56c51a0-d439-11e7-8f48-ac7a0445a03a.png">

**Comment by hauseja3** [comment]
And I am using the same version of cocoapods `1.3.1` and XCode `9.1`

**Comment by zanomar1** [comment]
This is really interesting...
Do you see the "blue hammer" indicating that Xcode is using the New Build System?

Here's a screenshot with it and the build error I'm running into:
![screen shot 2017-11-28 at 13 09 03](https://user-images.githubusercontent.com/20814614/33319087-6c6400e8-d43d-11e7-9c18-359afc577cee.png)

**Comment by hauseja3** [comment]
@zanomar1 this is what I needed! My apologies, I omitted the key phrase `New Build System`. Sorry and let me investigate this deeper. I will let you know.

**Comment by zanomar1** [comment]
Ha, no worries! 🙂 Thanks!!

**Comment by hauseja3** [comment]
Hi @zanomar1, I successfully built Core + LockerUI with new LockerUI version `3.0.1`. It should work fine now, please let me know after you check it.

**Comment by zanomar1** [comment]
Builds fine for me 🎉 
Thanks for all the efforts!
