### ISSUE TITLE
LABiometryType Deprecation

### ISSUE THREAD

**Issue by zanomar1** [Ceskasporitelna/cs-locker-ui-sdk-ios#14]
`LABiometryType.typeFaceID` changed to `LABiometryType.faceID` with Xcode 9.2:
https://developer.apple.com/documentation/localauthentication/labiometrytype/2928218-faceid?changes=latest_minor

**Comment by hauseja3** [comment]
Hi @zanomar1, I will check your PR and process it through CI. Thanks in advance.

**Comment by hauseja3** [comment]
Hi @zanomar1, Thanks for your participation. I am gonna release new version

**Comment by zanomar1** [comment]
Sure thing! 🙂 Thanks
