### ISSUE TITLE
Update the logo of Česká spořitelna

### ISSUE THREAD

**Issue by arhus** [Ceskasporitelna/cs-locker-ui-sdk-ios#22]
Please update the logo of Česká spořitelna. The vector file is available on the csas.cz website: https://www.csas.cz/content/dam/cz/csas/www_csas_cz/obrazky/obecne/ceska-sporitelna-logo.svg.

**Comment by hauseja3** [comment]
Hi @arhus, thanks for your note. It will be fixed in new release.
