### ISSUE TITLE
Aplikacia pada pri refresh Login Webview

### ISSUE THREAD

**Issue by Surko** [Ceskasporitelna/cs-locker-ui-sdk-ios#24]
Nefunguje refresh tlacitko na Webviewcontrolleri. Aplikacia spadne

![img_0016](https://user-images.githubusercontent.com/3267364/37093643-589c33de-2210-11e8-8100-54b343f76e1c.png)

Problem spociva pri volani _makeUrlRequest_ kde sa vola _self.activityIndicator.startAnimating()_ .
ActivityIndicator je ale v tejto chvili uz nil pretoze pri vstupe na tuto obrazovku sa prevedie metoda _stopAnimating_, ktora vymaze nadradeny kontajner _overlayView_.

**Comment by hauseja3** [comment]
Ahoj @Surko, diky koukneme na to. Plz @nevyhostenyv mužes na to kouknout?

**Comment by arhus** [comment]
Mohu poprosit o info o aktuálním stavu řešení této chyby?

**Comment by nevyhostenyv** [comment]
Zdravím, je to vyřešené. PR čeká na merge.

**Comment by hauseja3** [comment]
@nevyhostenyv @arhus merged.

**Comment by hauseja3** [comment]
It will be released in version 3.3.2 after retest.
