### ISSUE TITLE
Navigation bar color

### ISSUE THREAD

**Issue by hauseja3** [Ceskasporitelna/cs-locker-ui-sdk-ios#3]
Make it possible to change navigation bar color & tint color via `LockerUIOptions`

**Comment by nevyhostenyv** [comment]
@Vratislav Currently, there is possible to set the LockerUIOptions.navBarColor to default or white. You need to set the navBarColor to any color?
And regarding the tint color, adding UINavigationBar.appearance.setTintColor() in the application delegate solves not this issue?

**Comment by hauseja3** [comment]
FYI @David-Kr

**Comment by hauseja3** [comment]
@nevyhostenyv let's provide the same solution for the navigation bar color as in android. The thing is to provide an interface to set custom navigation bar color. 

We provide the interface both the ways as follows: 

`LockerUIOptions.setNavBarColor(CsNavBarColor)` default/white
`LockerUIOptions.setNavBarColor(customColor)` custom color
