### ISSUE TITLE
Cancel button options

### ISSUE THREAD

**Issue by hauseja3** [Ceskasporitelna/cs-locker-ui-sdk-ios#4]
Make it possible to hide cancel button via `AuthFlowOptions`. (not working at the moment) 

![img_6718](https://user-images.githubusercontent.com/13918426/27283835-6f700d8e-54f6-11e7-806d-9a2817ce06bb.PNG)

**Comment by nevyhostenyv** [comment]
![simulator screen shot 20 jun 2017 21 42 48](https://user-images.githubusercontent.com/15125876/27352580-7ae415fa-5601-11e7-8bd1-787f5618cb7b.png)
![simulator screen shot 20 jun 2017 21 42 56](https://user-images.githubusercontent.com/15125876/27352579-7ae28f14-5601-11e7-93db-c3e80928ed26.png)
When I turn on the "Hide cancel button" switch, it works. What is the exact approach to reproduce this issue?

**Comment by hauseja3** [comment]
FYI @David-Kr
