### ISSUE TITLE
Replace activity indicator with system indicator. 

### ISSUE THREAD

**Issue by hauseja3** [Ceskasporitelna/cs-locker-ui-sdk-ios#5]
Replace activity indicator in navigation bar with system indicator in status bar. 

![img_6719](https://user-images.githubusercontent.com/13918426/27283873-ae2944dc-54f6-11e7-932f-babb529b934c.PNG)

**Comment by nevyhostenyv** [comment]
If you mean a spinning wheel in the status bar, this indicator is on iOS usually reserved for network activities running in the background. Did you not rather mean the spinning wheel in the middle of the screen?

**Comment by hauseja3** [comment]
FYI @David-Kr

**Comment by hauseja3** [comment]
@nevyhostenyv this issue is tracked here https://github.com/Ceskasporitelna/cs-core-sdk-ios/issues/1
